# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-URL: https://spdx.org/licenses/GPL-2.0-or-later.html
#
# Copyright (C) 2026 Azzurra IRC Network (https://www.azzurra.chat/)

include ../../extra.mk

PROG = dbconv${PROG_SUFFIX}
SRCS =          \
    chanserv.c  \
    common.c    \
    datafiles.c \
    main.c      \
    memoserv.c  \
    nickserv.c  \
    storage.c

include ../../buildsys.mk

build: all
