#!/usr/bin/env python3
# langcomp.py — compile Azzurra services .lang sources to svc{IT,US,ES,FR}.clng.
#
# Python replacement for the i386 `langcomp` binary, so 64-bit builds don't need
# multilib/32-bit deps. Matches the 64-bit on-disk format read by src/lang.c
# (see inc/lang.h LANG_FILE_HEADER / LANG_FILE_MSG_HEADER).
#
# .lang format:
#   NAME_IN_CAPS            <-- flush-left line, one per message
#   <TAB>body line 1        <-- one or more tab-indented body lines
#   <TAB>body line 2        <-- joined with \n, no trailing \n
#
# Message ID = 0-indexed position in file (monotonic). inc/lang_msg_svc.h
# mirrors that order — each #define's value = its position in English.lang
# (the canonical ordering). The original i386 langcomp emitted this header
# too; we do the same so adding a message only requires editing .lang files.
#
# Usage:
#   langcomp.py [--lang-dir DIR] [--out-dir DIR] [--header PATH] [--no-header]
#
# Defaults assume services repo layout:
#   <repo>/lang/*.lang  ->  <repo>/run/data/lang/svc{0..3}.clng
#                      ->  <repo>/inc/lang_msg_svc.h

import argparse
import os
import struct
import sys
import time

SIGNATURE = 0x1BE1A208
VERSION = 1

# (lang_id, short, source, native-name, english-name)
LANGS = [
    (0, 'IT', 'Italian.lang', 'Italiano', 'Italian'),
    (1, 'US', 'English.lang', 'English',  'English'),
    (2, 'ES', 'Spanish.lang', 'Espa\xf1ol',  'Spanish'),
    (3, 'FR', 'French.lang',  'Francais', 'French'),
]


def parse_lang(path):
    entries = []
    name = None
    body = []
    with open(path, 'rb') as f:
        for line in f:
            raw = line.rstrip(b'\r\n')
            if not raw:
                continue
            if raw[:1] == b'\t':
                body.append(raw[1:])
                continue
            if raw[:1] == b'#':
                continue
            if name is not None:
                entries.append((name, b'\n'.join(body)))
            name = raw.strip()
            body = []
        if name is not None:
            entries.append((name, b'\n'.join(body)))
    return entries


def build_clng(lang_id, short, native, english, entries, created):
    short_field = short.encode('ascii') + b'\x00'
    if len(short_field) != 3:
        raise ValueError(f'short code must be 2 ASCII chars: {short!r}')
    loc = native.encode('latin-1')
    eng = english.encode('latin-1')

    # LANG_FILE_HEADER (32 bytes):
    #   uint32 version, lang_id, created, standard_flags, message_count
    #   char[3] short, 1 byte pad, uint16 loc_size, uint16 eng_size, uint32 signature
    header = struct.pack(
        '<IIIII3sxHHI',
        VERSION, lang_id, created & 0xFFFFFFFF, 0, len(entries),
        short_field, len(loc), len(eng), SIGNATURE,
    )
    assert len(header) == 32

    out = bytearray(header)
    out += loc
    out += eng
    for idx, (_name, body) in enumerate(entries):
        # LANG_FILE_MSG_HEADER (8 bytes with 4-byte alignment):
        #   uint32 id, uint16 size, 2 bytes pad
        out += struct.pack('<IHxx', idx, len(body))
        out += body
    return bytes(out)


HEADER_PREAMBLE = (
    '/***************************************/\n'
    '/*   Azzurra IRC Services Lang Index   */\n'
    '/*                                     */\n'
    '/* This file is generated by langcomp. */\n'
    '/*  You shouldn\'t edit this by hand!   */\n'
    '/***************************************/\n'
    '\n'
    '#define LANG_VERS_CURRENT   LANG_VERS_A1\n'
    '#define LANG_FILE_SIGNATURE 0x1BE1A208\n'
    '\n'
)


def write_header(path, entries):
    """Emit inc/lang_msg_svc.h — one #define per entry, in file-position order
    (same order as English.lang), value = position. Mirrors the original
    i386 langcomp output so the C side picks up new messages after a rebuild."""
    n = len(entries)
    lines = [HEADER_PREAMBLE]
    for idx, (name, _body) in enumerate(entries):
        lines.append(f'#define {name.decode("ascii")}\t\t\t(LANG_MSG_ID) {idx}\n')
    lines.append('\n')
    lines.append(f'#define LANG_MSG_FIRST   0\n')
    lines.append(f'#define LANG_MSG_LAST    {n - 1}\n')
    lines.append(f'#define LANG_MSG_COUNT   {n}\n')
    with open(path, 'w', encoding='ascii') as g:
        g.write(''.join(lines))


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--lang-dir', default=None,
                    help='directory with *.lang sources (default: script dir)')
    ap.add_argument('--out-dir', default=None,
                    help='output directory for svc*.clng (default: ../run/data/lang)')
    ap.add_argument('--header', default=None,
                    help='output path for lang_msg_svc.h (default: ../inc/lang_msg_svc.h)')
    ap.add_argument('--no-header', action='store_true',
                    help='skip regenerating lang_msg_svc.h')
    args = ap.parse_args(argv)

    here = os.path.dirname(os.path.abspath(__file__))
    lang_dir = args.lang_dir or here
    out_dir = args.out_dir or os.path.normpath(
        os.path.join(here, '..', 'run', 'data', 'lang'))
    header_path = args.header or os.path.normpath(
        os.path.join(here, '..', 'inc', 'lang_msg_svc.h'))
    os.makedirs(out_dir, exist_ok=True)

    created = int(time.time())
    english_entries = None
    for lang_id, short, src, native, english in LANGS:
        path = os.path.join(lang_dir, src)
        entries = parse_lang(path)
        if short == 'US':
            english_entries = entries
        blob = build_clng(lang_id, short, native, english, entries, created)
        out_path = os.path.join(out_dir, f'svc{lang_id}.clng')
        with open(out_path, 'wb') as g:
            g.write(blob)
        print(f'[{short}] {src}: {len(entries)} msgs -> {out_path} ({len(blob)} bytes)')

    if not args.no_header and english_entries is not None:
        write_header(header_path, english_entries)
        print(f'[H]  lang_msg_svc.h: {len(english_entries)} defines -> {header_path}')


if __name__ == '__main__':
    main(sys.argv[1:])
