# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-URL: https://spdx.org/licenses/GPL-2.0-or-later.html
#
# Copyright (C) 2026 Azzurra IRC Network (https://www.azzurra.chat/)

include ../extra.mk

SUBDIRS = dbconv

include ../buildsys.mk
